# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11.0.5
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.5
        servers: '[{"id": "github", "username": "x-access-token", "password": "${GITHUB_TOKEN}"}]'

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -Dtestfx.headless=true
      env:
        GITHUB_TOKEN: ${{ github.token }}
