# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: publish

on:
  push:
    branches:
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11.05
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.5
        server-id: github

    - name: Build with Maven
      run: mvn -B package -Dtestfx.headless=true -DskipFxTests=true --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        mvn deploy -DskipTests
